// Generated by CoffeeScript 1.10.0
var Path, Q, assert, assertType, isType, ref, spawnSync, syncFs;

ref = require("type-utils"), isType = ref.isType, assert = ref.assert, assertType = ref.assertType;

spawnSync = require("child_process").spawnSync;

syncFs = require("io/sync");

Path = require("path");

Q = require("q");

module.exports = function(command, args, options) {
  if (isType(args, Object)) {
    options = args;
    args = null;
  }
  if (!isType(args, Array)) {
    args = command.split(" ");
    command = args.shift();
  }
  if (options == null) {
    options = {};
  }
  if (args == null) {
    args = [];
  }
  assertType(command, String);
  assertType(args, Array);
  assertType(options, Object);
  if (options.cwd == null) {
    options.cwd = process.cwd();
  }
  if (options.encoding == null) {
    options.encoding = "utf8";
  }
  assertType(options.cwd, String);
  if (!Path.isAbsolute(options.cwd)) {
    options.cwd = Path.resolve(process.cwd(), options.cwd);
  }
  assert(syncFs.isDir(options.cwd), "'options.cwd' must be a directory!");
  return Q["try"](function() {
    var proc;
    proc = spawnSync(command, args, options);
    if (proc.stderr.length > 0) {
      throw Error(proc.stderr.replace(/[\r\n]+$/, ""));
    }
    return proc.stdout.replace(/[\r\n]+$/, "");
  });
};
